spring:
  h2:
    console:
      enabled: true # console usage
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL # database url setting
    driver-class-name: org.h2.Driver # datasource driver setting
